import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const css = readFileSync(new URL('../src/css/app.css', import.meta.url), 'utf8');
const html = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const script = readFileSync(new URL('../src/js/app.js', import.meta.url), 'utf8');
const highlighter = readFileSync(new URL('../vendor/highlightjs/highlight.min.js', import.meta.url), 'utf8');

assert.match(css, /--editor-top:\s*6px/);
assert.match(css, /\.workspace\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0, 1fr\)/);
assert.match(css, /\.workspace\.compare-mode\s*\{\s*grid-template-columns:\s*var\(--split\) 8px minmax\(0, 1fr\)/);
assert.match(css, /\.syntax-layer,\s*\.code-stage textarea\s*\{[\s\S]*?padding:\s*var\(--editor-top\) 18px var\(--editor-bottom\)/);
assert.match(html, /id="comparePane"[^>]*hidden/);
assert.match(html, /id="foldControls"[^>]*class="fold-controls"/);
assert.match(html, /data-action="format"/);
assert.match(html, /data-action="collapse-all"/);
assert.match(html, /data-action="expand-all"/);
assert.match(html, /data-action="replace"/);
assert.match(html, /data-action="code-mode"/);
assert.match(html, /id="languageBadge"/);
assert.match(html, /src="\.\/vendor\/highlightjs\/highlight\.min\.js\?v=11\.11\.1"/);
assert.match(html, /id="replacePanel"[^>]*role="dialog"/);
assert.match(html, /id="primarySearchHighlights"[^>]*class="search-highlights"/);
assert.match(html, /id="compareSearchHighlights"[^>]*class="search-highlights"/);
assert.match(html, /id="errorLocation"/);
assert.match(html, /src="\.\/src\/js\/json-diagnostics\.js\?v=/);
assert.match(html, /src="\.\/src\/js\/editor-utils\.js\?v=/);
assert.match(html, /src="\.\/src\/js\/diff-utils\.js\?v=/);
assert.match(css, /\.fold-button\s*\{[\s\S]*?border-radius:\s*50%/);
assert.match(css, /\.fragment-copy-button\s*\{/);
assert.match(script, /const LARGE_TEXT_LENGTH = 150000/);
assert.match(script, /function visibleLines\(/);
assert.match(script, /itemCount:/);
assert.match(script, /function copyFragment\(/);
assert.match(script, /function collapseAllFolds\(/);
assert.match(script, /function enableBracketHover\(/);
assert.match(script, /function scheduleDiagnostics\(/);
assert.match(script, /data-bracket-offset/);
assert.match(script, /<span inert>/);
assert.doesNotMatch(script, /preventDefault\(\)[\s\S]{0,120}openPageSearch/);
assert.doesNotMatch(html, /id="pageSearch"/);
assert.match(css, /\.bracket-token\.matching-bracket/);
assert.match(css, /\.replace-panel\s*\{/);
assert.match(css, /\.search-hit\.current\s*\{/);
assert.match(script, /function replaceSelectedMatch\(/);
assert.match(script, /function replaceEveryMatch\(/);
assert.match(script, /function renderSearchHighlights\(/);
assert.match(script, /function refreshSearchHighlights\(/);
assert.match(script, /function setCodeMode\(/);
assert.match(script, /canonicalText = currentPrimaryText\(\);/);
assert.doesNotMatch(script, /请先修正 JSON，再开启代码模式/);
assert.match(script, /highlightAuto\(sample, CODE_LANGUAGES\)/);
assert.match(script, /function languageHint\(/);
assert.match(script, /language === 'plaintext'[\s\S]{0,160}languageBadge\.hidden = true/);
assert.match(script, /'sql'/);
assert.match(script, /每次打开默认保持单面板/);
assert.doesNotMatch(script, /saved\?\.compareMode\) setCompareMode/);
assert.match(highlighter, /Highlight\.js v11\.11\.1/);
assert.match(script, /event\.ctrlKey[\s\S]{0,100}event\.key\.toLowerCase\(\) === 'h'/);
assert.match(script, /window\.addEventListener\('beforeunload', saveState\)/);
assert.match(script, /compressedState/);
assert.match(script, /window\.JsonBoardDiff\.lineDiff/);
assert.doesNotMatch(script, /fallbackDiff|LARGE_DIFF_CELLS/);
assert.doesNotMatch(html, /treeView|source-pane|result-pane/);

console.log('layout contract: single editor, inline folding, virtualized highlighting, split compare mode');
